server:
  port: 8889
  tomcat:
    max-threads: 5
    max-connections: 10
    min-spare-threads: 2
    accept-count: 5

spring:
  application:
    name: db-subscriber
  profiles:
    active: local
# canal server (单机客户端配置)
canal:
  server:
    ip: 47.244.150.124
    port: 11111
    # 默认订阅
    subscribe: minifranchise_dev\..*